### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by andrwlt** [atscaletech/grav#4]
**Tasks**

- [ ] Backend (Directus) deployment
- [ ] SDK CDN deployment
- [ ] Hosted checkout deployment

**Notes**

- Using Github flow
- Backend should be deployed in AWS
- Hosted checkout page should be deployed on https://spheron.network/
